/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#3e0110",
        "primary-container": "#5b1623",
        "primary-fixed": "#ffdadc",
        "primary-fixed-dim": "#ffb2b9",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#3f0110",
        "on-primary-fixed-variant": "#792d39",
        "on-primary-container": "#dc7b86",
        secondary: "#9e3e4c",
        "secondary-container": "#fd8896",
        "secondary-fixed": "#ffdadb",
        "secondary-fixed-dim": "#ffb2b9",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#761f2f",
        "on-secondary-fixed": "#40000f",
        "on-secondary-fixed-variant": "#7f2736",
        tertiary: "#735c00",
        "tertiary-container": "#cba72f",
        "tertiary-fixed": "#ffe088",
        "tertiary-fixed-dim": "#e9c349",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4e3d00",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#574500",
        surface: "#fdf9f6",
        "surface-dim": "#ddd9d6",
        "surface-bright": "#fdf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f3f0",
        "surface-container": "#f1edea",
        "surface-container-high": "#ebe7e4",
        "surface-container-highest": "#e5e2df",
        "surface-variant": "#e5e2df",
        "on-surface": "#1c1b1a",
        "on-surface-variant": "#544244",
        "inverse-surface": "#31302f",
        "inverse-on-surface": "#f4f0ed",
        "inverse-primary": "#ffb2b9",
        background: "#fdf9f6",
        "on-background": "#1c1b1a",
        outline: "#877273",
        "outline-variant": "#d9c1c2",
        "surface-tint": "#97444f",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        gold: "#D4AF37",
        burgundy: "#5B1623",
        cream: "#F8F4F1",
      },
      fontFamily: {
        display: ['"Playfair Display"', "serif"],
        body: ["Poppins", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.1em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "120px",
        "element-gap": "16px",
        "container-max": "1280px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      boxShadow: {
        ambient: "0 10px 40px -10px rgba(91, 22, 35, 0.08)",
        "ambient-lg": "0 20px 50px -12px rgba(91, 22, 35, 0.08)",
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "bounce-slow": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(8px)" },
        },
        glow: {
          from: { boxShadow: "0 0 10px rgba(212, 175, 55, 0.2)" },
          to: { boxShadow: "0 0 30px rgba(212, 175, 55, 0.5)" },
        },
      },
      animation: {
        "fade-in": "fade-in 1.2s ease-out forwards",
        "fade-in-up": "fade-in-up 0.8s ease-out forwards",
        "bounce-slow": "bounce-slow 2s ease-in-out infinite",
        glow: "glow 2s ease-in-out infinite alternate",
      },
    },
  },
  plugins: [],
};
